name: Test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.8', '3.9', '3.10', '3.11']
        include:
          - os: ubuntu-20.04
            python: '3.6'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and tox-gh-actions
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox
